services:
  - type: web
    name: sales-dashboard
    runtime: node
    rootDir: sales-backend
    buildCommand: npm install && cd ../sales-frontend && npm install && npm run build
    startCommand: node sqlite/initDB.js && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
